"""Combine on-disk general.yaml + qtype_*.yaml into the runtime rubric template.

No LLM calls — pure file concat with type_aliases header.
"""
from pathlib import Path

GENERATION_DIR = Path(__file__).resolve().parent
RUBRIC_DIR = GENERATION_DIR.parent
OUT_DIR = RUBRIC_DIR / 'artifacts/distilled'
RUNTIME_TEMPLATE = RUBRIC_DIR / 'rubric_templates.yaml'

QTYPE_KEYS = {
    "Action Reasoning":      "action_reasoning",
    "Action Recognition":    "action_recognition",
    "Attribute Perception":  "attribute_perception",
    "Counting Problem":      "counting_problem",
    "Information Synopsis":  "information_synopsis",
    "OCR Problems":          "ocr_problems",
    "Object Reasoning":      "object_reasoning",
    "Object Recognition":    "object_recognition",
    "Spatial Perception":    "spatial_perception",
    "Spatial Reasoning":     "spatial_reasoning",
    "Temporal Perception":   "temporal_perception",
    "Temporal Reasoning":    "temporal_reasoning",
}

general_yaml = (OUT_DIR / 'general.yaml').read_text()
qtype_yamls = {}
for qtype, qkey in QTYPE_KEYS.items():
    p = OUT_DIR / f'qtype_{qkey}.yaml'
    if p.exists():
        qtype_yamls[qtype] = p.read_text()

combined = [
    '# Auto-generated by src.rubric.generation.combine — DO NOT EDIT BY HAND.',
    '# Distilled by Qwen3.5-27B from per-question rubrics generated by Qwen3.5-27B.',
    '',
    general_yaml,
    '',
    '# Map VideoMME question_type → snake_case template key.',
    'type_aliases:',
]
for qtype, qkey in QTYPE_KEYS.items():
    if qtype in qtype_yamls:
        combined.append(f'  {qtype!r}: {qkey}')

combined.extend(['', '# Per-qtype templates', 'templates:'])
for qtype, qkey in QTYPE_KEYS.items():
    if qtype not in qtype_yamls:
        continue
    block = qtype_yamls[qtype]
    indented = '\n'.join('  ' + line for line in block.split('\n'))
    combined.append(indented)
    combined.append('')

combined_text = '\n'.join(combined)
out = OUT_DIR / 'rubric_templates_v2.yaml'
out.write_text(combined_text)
RUNTIME_TEMPLATE.write_text(combined_text)
print(f'wrote {out} and {RUNTIME_TEMPLATE} ({len(combined_text)} chars)')
