"""Re-run only Phase 2b (general) + Phase 2c (combine) using existing qtype_*.yaml.

Skips question-type distillation and uses existing qtype_{key}.yaml files.
"""
from __future__ import annotations
import argparse
import itertools
import re
import threading
from pathlib import Path

import requests

GENERATION_DIR = Path(__file__).resolve().parent
RUBRIC_DIR = GENERATION_DIR.parent
OUT_DIR = RUBRIC_DIR / 'artifacts/distilled'
PROMPT_DIR = GENERATION_DIR / 'prompts'
RUNTIME_TEMPLATE = RUBRIC_DIR / 'templates/generated_v2.yaml'

QWEN_MODEL = 'Qwen3.5-27B'
QWEN_URLS_DEFAULT = (
    'http://127.0.0.1:8000/v1/chat/completions,'
    'http://127.0.0.1:8001/v1/chat/completions,'
    'http://127.0.0.1:8003/v1/chat/completions,'
    'http://10.82.1.145:8003/v1/chat/completions'
)

QTYPE_KEYS = {
    "Action Reasoning":      "action_reasoning",
    "Action Recognition":    "action_recognition",
    "Attribute Perception":  "attribute_perception",
    "Counting Problem":      "counting_problem",
    "Information Synopsis":  "information_synopsis",
    "OCR Problems":          "ocr_problems",
    "Object Reasoning":      "object_reasoning",
    "Object Recognition":    "object_recognition",
    "Spatial Perception":    "spatial_perception",
    "Spatial Reasoning":     "spatial_reasoning",
    "Temporal Perception":   "temporal_perception",
    "Temporal Reasoning":    "temporal_reasoning",
}


def call_qwen(session, url, system_prompt, user_msg, max_tokens=8000):
    payload = {
        "model": QWEN_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_msg},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.0,
        "chat_template_kwargs": {"enable_thinking": False},
    }
    resp = session.post(url, json=payload, timeout=600)
    resp.raise_for_status()
    return resp.json()['choices'][0]['message']['content']


def extract_yaml(raw: str) -> str:
    m = re.search(r'```ya?ml\s*\n(.*?)\n```', raw, re.DOTALL)
    if m:
        return m.group(1).strip()
    m = re.search(r'```\s*\n(.*?)\n```', raw, re.DOTALL)
    if m:
        return m.group(1).strip()
    return raw.strip()


def format_general_user_msg(qtype_yamls):
    parts = ['You have question-type rubrics below. Produce the general rubric.\n']
    for qtype, yaml_str in qtype_yamls.items():
        parts.append(f'\n--- question_type: {qtype} ---\n{yaml_str}')
    return '\n'.join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--qwen-urls', type=str, default=QWEN_URLS_DEFAULT)
    args = ap.parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    urls = [u.strip() for u in args.qwen_urls.split(',') if u.strip()]
    print(f'qwen endpoints ({len(urls)})')
    session = requests.Session()
    cycle = itertools.cycle(urls)
    lock = threading.Lock()
    def pick():
        with lock:
            return next(cycle)

    qtype_yamls = {}
    for qtype, qkey in QTYPE_KEYS.items():
        p = OUT_DIR / f'qtype_{qkey}.yaml'
        if not p.exists():
            print(f'  SKIP {qtype}: {p} missing')
            continue
        qtype_yamls[qtype] = p.read_text()
        print(f'  loaded qtype_{qkey}.yaml ({len(qtype_yamls[qtype])} chars)')

    print('\n=== Phase 2b (re-run): general distillation ===')
    general_system = (PROMPT_DIR / 'distill_general.md').read_text()
    user_msg = format_general_user_msg(qtype_yamls)
    raw = call_qwen(session, pick(), general_system, user_msg, max_tokens=8000)
    yaml_part = extract_yaml(raw)
    (OUT_DIR / 'general.raw.txt').write_text(raw)
    (OUT_DIR / 'general.yaml').write_text(yaml_part)
    print(f'  wrote general.yaml ({len(yaml_part)} chars)')

    print('\n=== Phase 2c (re-run): combine ===')
    combined = [
        '# Auto-generated by src.rubric.generation.rerun_general — DO NOT EDIT BY HAND.',
        '# Distilled by Qwen3.5-27B from per-question rubrics generated by Qwen3.5-27B (+ optional claude-opus-4-7).',
        '',
        yaml_part,
        '',
        '# Map VideoMME question_type → snake_case template key.',
        'type_aliases:',
    ]
    for qtype, qkey in QTYPE_KEYS.items():
        if qtype in qtype_yamls:
            combined.append(f'  {qtype!r}: {qkey}')
    combined.append('')
    combined.append('# Per-qtype templates')
    combined.append('templates:')
    for qtype, qkey in QTYPE_KEYS.items():
        if qtype not in qtype_yamls:
            continue
        block = qtype_yamls[qtype]
        indented = '\n'.join('  ' + line for line in block.split('\n'))
        combined.append(indented)
        combined.append('')
    combined_text = '\n'.join(combined)
    (OUT_DIR / 'rubric_templates_v2.yaml').write_text(combined_text)
    RUNTIME_TEMPLATE.write_text(combined_text)
    print(f'  wrote rubric_templates_v2.yaml and {RUNTIME_TEMPLATE}')


if __name__ == '__main__':
    main()
