"""Verifier — judge whether the evidence chain satisfies the rubric.

Input:  question + options + evidence chain + rubric
Output: label (sufficient / insufficient)
        if insufficient → missing_evidence {type, description}
"""
from __future__ import annotations

from typing import Dict, List, Optional

from utils.jsonx import as_str, extract_json

VERIFIER_SYS = """You evaluate whether retrieved video-segment evidence is sufficient to answer
a multiple-choice question, judged against a rubric that defines sufficiency criteria.

## Evidence Chain
Each entry is a text description of a retrieved video segment.

## Judgment rules
- Compare the evidence against the rubric strictly.
- If the evidence directly supports one option and the rubric criteria are met → sufficient.
- If any rubric criterion is unmet, or the evidence is ambiguous → insufficient.

## Output
Return ONLY a strict JSON object, no prose, no markdown fences.

If sufficient:
{"label": "sufficient", "missing_evidence": null}

If insufficient:
{
  "label": "insufficient",
  "missing_evidence": {
    "type": "<one of: temporal | visual | count | identity | causal | comparative | other>",
    "description": "<one sentence: what specific evidence is still needed>"
  }
}
"""


def _format_evidence(evidence_texts: List[str]) -> str:
    if not evidence_texts:
        return "(no evidence retrieved yet)"
    return "\n".join(f"[E{i+1}] {t}" for i, t in enumerate(evidence_texts))


class Verifier:
    def __init__(self, llm):
        self.llm = llm

    def verify(
        self,
        question: str,
        candidates: List[str],
        evidence_texts: List[str],
        rubric: str,
    ) -> Dict:
        """Judge evidence sufficiency.

        Args:
            question:       The question text.
            candidates:     Answer option strings.
            evidence_texts: Retrieved memory chunk texts (evidence chain).
            rubric:         Sufficiency criteria generated by Planner on first call.

        Returns:
            {
                "label":            "sufficient" | "insufficient",
                "missing_evidence": None | {"type": str, "description": str}
            }
        """
        opts = "\n".join(f"  ({chr(ord('A')+i)}) {c}" for i, c in enumerate(candidates))
        ev   = _format_evidence(evidence_texts)
        rubric_block = f"\nRubric: {rubric}" if rubric else ""

        user = (
            f"Question: {question}\n"
            f"Options:\n{opts}"
            f"{rubric_block}\n\n"
            f"Evidence Chain:\n{ev}\n\n"
            "Return the JSON now."
        )
        messages = [
            {"role": "system", "content": VERIFIER_SYS},
            {"role": "user",   "content": user},
        ]
        raw    = self.llm.chat(messages, max_new_tokens=128, enable_thinking=False)
        parsed = extract_json(raw)

        label   = as_str(parsed.get("label", "insufficient")).lower()
        if label not in ("sufficient", "insufficient"):
            label = "insufficient"

        missing = parsed.get("missing_evidence")
        if label == "sufficient" or not isinstance(missing, dict):
            missing = None
        else:
            missing = {
                "type":        as_str(missing.get("type",        "other")),
                "description": as_str(missing.get("description", "")),
            }

        return {"label": label, "missing_evidence": missing}
